"""
Static Questions Bank for Daily Quiz
200 Questions: 100 English + 100 Hindi
No API calls needed - just pure static data
"""

ENGLISH_QUESTIONS = [
    # 0-9
    {"question": "What is the capital of France?", "options": ["London", "Berlin", "Paris", "Madrid"], "correct": 2, "category": "geography"},
    {"question": "Which planet is closest to the Sun?", "options": ["Venus", "Mercury", "Earth", "Mars"], "correct": 1, "category": "science"},
    {"question": "What is the largest ocean on Earth?", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "correct": 3, "category": "geography"},
    {"question": "Who wrote 'Romeo and Juliet'?", "options": ["Milton", "Shakespeare", "Marlowe", "Bacon"], "correct": 1, "category": "literature"},
    {"question": "What is the chemical symbol for Gold?", "options": ["Go", "Gd", "Au", "Ag"], "correct": 2, "category": "science"},
    {"question": "Which country has the Great Wall?", "options": ["Japan", "China", "India", "Korea"], "correct": 1, "category": "geography"},
    {"question": "What is the smallest prime number?", "options": ["0", "1", "2", "3"], "correct": 2, "category": "math"},
    {"question": "Who painted the Mona Lisa?", "options": ["Michelangelo", "Leonardo da Vinci", "Raphael", "Botticelli"], "correct": 1, "category": "art"},
    {"question": "What is the capital of Japan?", "options": ["Osaka", "Kyoto", "Tokyo", "Yokohama"], "correct": 2, "category": "geography"},
    {"question": "Which animal is the fastest land mammal?", "options": ["Lion", "Horse", "Cheetah", "Antelope"], "correct": 2, "category": "biology"},
    # 10-19
    {"question": "What is 15 × 4?", "options": ["50", "60", "70", "80"], "correct": 1, "category": "math"},
    {"question": "Which country is home to the Eiffel Tower?", "options": ["Italy", "France", "Spain", "Germany"], "correct": 1, "category": "geography"},
    {"question": "What does H2O represent?", "options": ["Hydrogen", "Salt", "Water", "Oxygen"], "correct": 2, "category": "science"},
    {"question": "How many continents are there?", "options": ["5", "6", "7", "8"], "correct": 2, "category": "geography"},
    {"question": "What is the capital of Germany?", "options": ["Munich", "Berlin", "Hamburg", "Cologne"], "correct": 1, "category": "geography"},
    {"question": "Which gas do plants absorb?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], "correct": 2, "category": "science"},
    {"question": "What year did World War II end?", "options": ["1943", "1944", "1945", "1946"], "correct": 2, "category": "history"},
    {"question": "Which is the longest river in the world?", "options": ["Amazon", "Nile", "Yangtze", "Mississippi"], "correct": 1, "category": "geography"},
    {"question": "What is the freezing point of water in Celsius?", "options": ["-10", "0", "10", "32"], "correct": 1, "category": "science"},
    {"question": "Who was the first President of USA?", "options": ["Jefferson", "Washington", "Lincoln", "Kennedy"], "correct": 1, "category": "history"},
    # 20-29
    {"question": "What is the chemical formula for sulfuric acid?", "options": ["H2SO3", "H2SO4", "HSO4", "H3SO4"], "correct": 1, "category": "science"},
    {"question": "Which Shakespeare play features the ghost of Hamlet's father?", "options": ["Macbeth", "Othello", "Hamlet", "King Lear"], "correct": 2, "category": "literature"},
    {"question": "What is the capital of Australia?", "options": ["Sydney", "Melbourne", "Canberra", "Brisbane"], "correct": 2, "category": "geography"},
    {"question": "How many sides does a hexagon have?", "options": ["5", "6", "7", "8"], "correct": 1, "category": "math"},
    {"question": "Which country is the largest by area?", "options": ["Canada", "USA", "Russia", "China"], "correct": 2, "category": "geography"},
    {"question": "What is the speed of light?", "options": ["300,000 km/s", "3,000 km/s", "30,000 km/s", "3,000,000 km/s"], "correct": 0, "category": "science"},
    {"question": "Who wrote '1984'?", "options": ["Ray Bradbury", "George Orwell", "Aldous Huxley", "Isaac Asimov"], "correct": 1, "category": "literature"},
    {"question": "What is the capital of India?", "options": ["Mumbai", "New Delhi", "Bangalore", "Chennai"], "correct": 1, "category": "geography"},
    {"question": "How many bones are in the human body?", "options": ["186", "206", "226", "246"], "correct": 1, "category": "biology"},
    {"question": "What is the atomic number of Carbon?", "options": ["4", "6", "8", "12"], "correct": 1, "category": "science"},
    # 30-39
    {"question": "Which planet is known as the Red Planet?", "options": ["Venus", "Jupiter", "Mars", "Saturn"], "correct": 2, "category": "science"},
    {"question": "What is 25% of 200?", "options": ["25", "50", "75", "100"], "correct": 1, "category": "math"},
    {"question": "Who invented the telephone?", "options": ["Edison", "Bell", "Tesla", "Marconi"], "correct": 1, "category": "history"},
    {"question": "What is the capital of Spain?", "options": ["Barcelona", "Madrid", "Valencia", "Seville"], "correct": 1, "category": "geography"},
    {"question": "How many strings does a violin have?", "options": ["3", "4", "5", "6"], "correct": 1, "category": "music"},
    {"question": "What is the chemical symbol for Iron?", "options": ["Ir", "Fe", "In", "I"], "correct": 1, "category": "science"},
    {"question": "Which ocean is the deepest?", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "correct": 3, "category": "geography"},
    {"question": "What is the capital of Brazil?", "options": ["Rio de Janeiro", "Brasília", "São Paulo", "Salvador"], "correct": 1, "category": "geography"},
    {"question": "How many planets are in our solar system?", "options": ["7", "8", "9", "10"], "correct": 1, "category": "science"},
    {"question": "What year did the Titanic sink?", "options": ["1912", "1913", "1914", "1915"], "correct": 0, "category": "history"},
    # 40-49
    {"question": "What is the capital of Kazakhstan?", "options": ["Almaty", "Astana", "Karaganda", "Shymkent"], "correct": 1, "category": "geography"},
    {"question": "Who wrote 'War and Peace'?", "options": ["Dostoevsky", "Tolstoy", "Chekhov", "Turgenev"], "correct": 1, "category": "literature"},
    {"question": "What is the Heisenberg Uncertainty Principle about?", "options": ["Energy conservation", "Position and momentum", "Wave-particle duality", "Quantum entanglement"], "correct": 1, "category": "science"},
    {"question": "Which ancient wonder is still standing?", "options": ["Hanging Gardens", "Colossus", "Pyramid of Giza", "Lighthouse of Alexandria"], "correct": 2, "category": "history"},
    {"question": "What is the molecular weight of H2O?", "options": ["16", "18", "20", "22"], "correct": 1, "category": "science"},
    {"question": "Who was the first Holy Roman Emperor?", "options": ["Otto I", "Charlemagne", "Frederick II", "Charles V"], "correct": 1, "category": "history"},
    {"question": "What is the capital of Kyrgyzstan?", "options": ["Osh", "Bishkek", "Jalalabad", "Karakol"], "correct": 1, "category": "geography"},
    {"question": "Which treaty ended World War I?", "options": ["Treaty of Brest-Litovsk", "Treaty of Versailles", "Treaty of Paris", "Treaty of Trianon"], "correct": 1, "category": "history"},
    {"question": "What is the charge of an electron?", "options": ["Positive", "Negative", "Neutral", "Variable"], "correct": 1, "category": "science"},
    {"question": "Who composed 'The Magic Flute'?", "options": ["Beethoven", "Mozart", "Haydn", "Brahms"], "correct": 1, "category": "music"},
    # 50-59
    {"question": "What is the capital of Uzbekistan?", "options": ["Samarkand", "Tashkent", "Bukhara", "Andijan"], "correct": 1, "category": "geography"},
    {"question": "Which philosopher wrote 'Critique of Pure Reason'?", "options": ["Descartes", "Kant", "Hegel", "Leibniz"], "correct": 1, "category": "philosophy"},
    {"question": "What is the speed of sound?", "options": ["300 m/s", "343 m/s", "1000 m/s", "3000 m/s"], "correct": 1, "category": "science"},
    {"question": "Who discovered penicillin?", "options": ["Koch", "Fleming", "Pasteur", "Lister"], "correct": 1, "category": "science"},
    {"question": "What is the capital of Mongolia?", "options": ["Ulaanbaatar", "Darhan", "Khovd", "Erdenet"], "correct": 0, "category": "geography"},
    {"question": "Which artist cut off his own ear?", "options": ["Picasso", "Matisse", "Van Gogh", "Dali"], "correct": 2, "category": "art"},
    {"question": "What is Avogadro's number?", "options": ["6.02 x 10^23", "3.14 x 10^23", "9.81 x 10^23", "1.38 x 10^23"], "correct": 0, "category": "science"},
    {"question": "Who wrote 'Ulysses'?", "options": ["Virginia Woolf", "James Joyce", "Samuel Beckett", "Ezra Pound"], "correct": 1, "category": "literature"},
    {"question": "What is the largest gland in the human body?", "options": ["Pancreas", "Thyroid", "Liver", "Adrenal"], "correct": 2, "category": "biology"},
    {"question": "Which country hosted the 2016 Olympics?", "options": ["China", "Brazil", "Japan", "France"], "correct": 1, "category": "sports"},
    # 60-69
    {"question": "What is the chemical formula for table salt?", "options": ["NaCl", "KCl", "CaCl2", "MgCl2"], "correct": 0, "category": "science"},
    {"question": "How many sides does an octagon have?", "options": ["6", "7", "8", "9"], "correct": 2, "category": "math"},
    {"question": "What is the capital of Portugal?", "options": ["Porto", "Lisbon", "Covilhã", "Braga"], "correct": 1, "category": "geography"},
    {"question": "Who invented the electric light bulb?", "options": ["Tesla", "Edison", "Swan", "Davy"], "correct": 1, "category": "history"},
    {"question": "What is 10% of 500?", "options": ["25", "50", "75", "100"], "correct": 1, "category": "math"},
    {"question": "Which country is the smallest by area?", "options": ["Monaco", "Liechtenstein", "Vatican City", "San Marino"], "correct": 2, "category": "geography"},
    {"question": "What is the capital of Greece?", "options": ["Thessaloniki", "Athens", "Patras", "Heraklion"], "correct": 1, "category": "geography"},
    {"question": "How many chambers does a human heart have?", "options": ["2", "3", "4", "5"], "correct": 2, "category": "biology"},
    {"question": "What is the symbol for Potassium?", "options": ["Po", "K", "Pt", "Pb"], "correct": 1, "category": "science"},
    {"question": "Who wrote 'The Great Gatsby'?", "options": ["Hemingway", "F. Scott Fitzgerald", "Steinbeck", "Faulkner"], "correct": 1, "category": "literature"},
    # 70-79
    {"question": "What is the capital of Turkey?", "options": ["Istanbul", "Ankara", "Izmir", "Bursa"], "correct": 1, "category": "geography"},
    {"question": "How many inches are in a foot?", "options": ["10", "12", "15", "16"], "correct": 1, "category": "math"},
    {"question": "Which gas is used for welding?", "options": ["Nitrogen", "Oxygen", "Argon", "Helium"], "correct": 2, "category": "science"},
    {"question": "Who invented the printing press?", "options": ["Gutenberg", "Caxton", "Jikji", "Bi Sheng"], "correct": 0, "category": "history"},
    {"question": "What is the capital of Belgium?", "options": ["Antwerp", "Brussels", "Ghent", "Bruges"], "correct": 1, "category": "geography"},
    {"question": "What is the largest mammal in the world?", "options": ["African Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], "correct": 1, "category": "biology"},
    {"question": "What is the boiling point of water in Celsius?", "options": ["90", "100", "110", "120"], "correct": 1, "category": "science"},
    {"question": "Who wrote 'Pride and Prejudice'?", "options": ["Emily Bronte", "Charlotte Bronte", "Jane Austen", "George Eliot"], "correct": 2, "category": "literature"},
    {"question": "What is the capital of Sweden?", "options": ["Gothenburg", "Stockholm", "Malmö", "Uppsala"], "correct": 1, "category": "geography"},
    {"question": "How many seconds are in a minute?", "options": ["50", "60", "70", "80"], "correct": 1, "category": "math"},
    # 80-89
    {"question": "What is the capital of Norway?", "options": ["Bergen", "Oslo", "Stavanger", "Trondheim"], "correct": 1, "category": "geography"},
    {"question": "Which planet has the most moons?", "options": ["Saturn", "Jupiter", "Uranus", "Neptune"], "correct": 1, "category": "science"},
    {"question": "What is 50 ÷ 2?", "options": ["20", "25", "30", "35"], "correct": 1, "category": "math"},
    {"question": "Who painted Starry Night?", "options": ["Monet", "Van Gogh", "Cézanne", "Renoir"], "correct": 1, "category": "art"},
    {"question": "What is the capital of Denmark?", "options": ["Aarhus", "Copenhagen", "Odense", "Aalborg"], "correct": 1, "category": "geography"},
    {"question": "How many chambers does a squid's heart have?", "options": ["2", "3", "4", "5"], "correct": 1, "category": "biology"},
    {"question": "What is the chemical symbol for Copper?", "options": ["Co", "Cu", "Cr", "Cd"], "correct": 1, "category": "science"},
    {"question": "Who wrote 'Moby Dick'?", "options": ["Mark Twain", "Herman Melville", "Nathaniel Hawthorne", "Washington Irving"], "correct": 1, "category": "literature"},
    {"question": "What is the capital of Finland?", "options": ["Tampere", "Turku", "Helsinki", "Espoo"], "correct": 2, "category": "geography"},
    {"question": "What is 7 × 8?", "options": ["54", "56", "58", "60"], "correct": 1, "category": "math"},
    # 90-99
    {"question": "What is the largest organ in the human body?", "options": ["Brain", "Heart", "Skin", "Liver"], "correct": 2, "category": "biology"},
    {"question": "Who was the first person to walk on the moon?", "options": ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Yuri Gagarin"], "correct": 1, "category": "history"},
    {"question": "What is the capital of Poland?", "options": ["Krakow", "Warsaw", "Gdansk", "Wroclaw"], "correct": 1, "category": "geography"},
    {"question": "What is the chemical symbol for Silver?", "options": ["Si", "Ag", "Au", "Al"], "correct": 1, "category": "science"},
    {"question": "How many strings does a guitar have?", "options": ["5", "6", "7", "8"], "correct": 1, "category": "music"},
    {"question": "Who wrote 'The Odyssey'?", "options": ["Sophocles", "Homer", "Herodotus", "Thucydides"], "correct": 1, "category": "literature"},
    {"question": "What is the capital of Hungary?", "options": ["Debrecen", "Budapest", "Szeged", "Miskolc"], "correct": 1, "category": "geography"},
    {"question": "What is 12 × 12?", "options": ["132", "144", "156", "168"], "correct": 1, "category": "math"},
    {"question": "Which element has atomic number 1?", "options": ["Helium", "Hydrogen", "Lithium", "Beryllium"], "correct": 1, "category": "science"},
    {"question": "What is the longest bone in the human body?", "options": ["Tibia", "Femur", "Humerus", "Fibula"], "correct": 1, "category": "biology"},
]

HINDI_QUESTIONS = [
    # 0-9
    {"question": "भारत की राजधानी कौन सी है?", "options": ["मुंबई", "नई दिल्ली", "कोलकाता", "बेंगलुरु"], "correct": 1, "category": "geography"},
    {"question": "विश्व का सबसे बड़ा महाद्वीप कौन सा है?", "options": ["अफ्रीका", "एशिया", "उत्तरी अमेरिका", "यूरोप"], "correct": 1, "category": "geography"},
    {"question": "भारत की सबसे लंबी नदी कौन सी है?", "options": ["यमुना", "गंगा", "ब्रह्मपुत्र", "नर्मदा"], "correct": 1, "category": "geography"},
    {"question": "भारत के कितने राज्य हैं?", "options": ["26", "28", "29", "30"], "correct": 1, "category": "geography"},
    {"question": "एशिया का सबसे बड़ा देश कौन सा है?", "options": ["भारत", "चीन", "इंडोनेशिया", "पाकिस्तान"], "correct": 1, "category": "geography"},
    {"question": "माउंट एवरेस्ट किस देश में स्थित है?", "options": ["भारत", "चीन", "नेपाल", "तिब्बत"], "correct": 2, "category": "geography"},
    {"question": "भारत का सबसे बड़ा शहर कौन सा है?", "options": ["दिल्ली", "बेंगलुरु", "मुंबई", "चेन्नई"], "correct": 0, "category": "geography"},
    {"question": "विश्व का सबसे ऊंचा पर्वत कौन सा है?", "options": ["के2", "कंचनजंगा", "माउंट एवरेस्ट", "लोहित"], "correct": 2, "category": "geography"},
    {"question": "भारत का सबसे पुराना शहर कौन सा है?", "options": ["दिल्ली", "आगरा", "वाराणसी", "अयोध्या"], "correct": 2, "category": "geography"},
    {"question": "अमेरिका की राजधानी कौन सी है?", "options": ["न्यूयॉर्क", "वाशिंगटन डीसी", "लॉस एंजिल्स", "शिकागो"], "correct": 1, "category": "geography"},
    # 10-19
    {"question": "पानी का रासायनिक सूत्र क्या है?", "options": ["H2O", "H2O2", "CO2", "O2"], "correct": 0, "category": "science"},
    {"question": "सूर्य के सबसे करीब ग्रह कौन सा है?", "options": ["शुक्र", "बुध", "पृथ्वी", "मंगल"], "correct": 1, "category": "science"},
    {"question": "हमारे सौरमंडल में कितने ग्रह हैं?", "options": ["7", "8", "9", "10"], "correct": 1, "category": "science"},
    {"question": "आयरन का प्रतीक क्या है?", "options": ["Ir", "Fe", "In", "I"], "correct": 1, "category": "science"},
    {"question": "प्रकाश की गति कितनी है?", "options": ["300,000 km/s", "150,000 km/s", "600,000 km/s", "1,000,000 km/s"], "correct": 0, "category": "science"},
    {"question": "सबसे बड़ा ग्रह कौन सा है?", "options": ["शनि", "बृहस्पति", "यूरेनस", "नेप्च्यून"], "correct": 1, "category": "science"},
    {"question": "पृथ्वी की परिक्रमा करने में कितना समय लगता है?", "options": ["365 दिन", "366 दिन", "364 दिन", "367 दिन"], "correct": 0, "category": "science"},
    {"question": "मानव शरीर में कितनी हड्डियां होती हैं?", "options": ["186", "196", "206", "216"], "correct": 2, "category": "science"},
    {"question": "हीरा किस का बना होता है?", "options": ["सिलिकॉन", "कार्बन", "ऑक्सीजन", "नाइट्रोजन"], "correct": 1, "category": "science"},
    {"question": "पानी कितने डिग्री पर जमता है?", "options": ["10°C", "0°C", "-10°C", "5°C"], "correct": 1, "category": "science"},
    # 20-29
    {"question": "भारत को आजादी कब मिली?", "options": ["1945", "1946", "1947", "1948"], "correct": 2, "category": "history"},
    {"question": "भारत के पहले राष्ट्रपति कौन थे?", "options": ["डॉ. राजेंद्र प्रसाद", "जवाहरलाल नेहरू", "सर्वपल्ली राधाकृष्णन", "एस. राधाकृष्णन"], "correct": 0, "category": "history"},
    {"question": "महात्मा गांधी का जन्म कब हुआ?", "options": ["1869", "1870", "1871", "1872"], "correct": 0, "category": "history"},
    {"question": "द्वितीय विश्व युद्ध कब समाप्त हुआ?", "options": ["1943", "1944", "1945", "1946"], "correct": 2, "category": "history"},
    {"question": "भारत के पहले प्रधानमंत्री कौन थे?", "options": ["महात्मा गांधी", "जवाहरलाल नेहरू", "सरदार पटेल", "डॉ. अंबेडकर"], "correct": 1, "category": "history"},
    {"question": "ताजमहल किसने बनवाया था?", "options": ["अकबर", "शाहजहां", "औरंगजेब", "हुमायूं"], "correct": 1, "category": "history"},
    {"question": "प्रथम विश्व युद्ध कब समाप्त हुआ?", "options": ["1917", "1918", "1919", "1920"], "correct": 1, "category": "history"},
    {"question": "अशोक का स्तंभ किस राजवंश का प्रतीक है?", "options": ["मौर्य", "गुप्त", "चोल", "कांची"], "correct": 0, "category": "history"},
    {"question": "भारत के संविधान को कब अंगीकार किया गया?", "options": ["1950", "1951", "1949", "1948"], "correct": 2, "category": "history"},
    {"question": "लाल किला किसने बनवाया था?", "options": ["अकबर", "शाहजहां", "औरंगजेब", "बाबर"], "correct": 1, "category": "history"},
    # 30-39
    {"question": "'रामायण' के लेखक कौन हैं?", "options": ["वेदव्यास", "वाल्मीकि", "तुलसीदास", "कालिदास"], "correct": 1, "category": "literature"},
    {"question": "'महाभारत' के रचयिता कौन हैं?", "options": ["वाल्मीकि", "वेदव्यास", "तुलसीदास", "बाणभट्ट"], "correct": 1, "category": "literature"},
    {"question": "रविंद्रनाथ टैगोर ने कौन सी पुस्तक लिखी?", "options": ["कुमारसंभव", "गीतांजलि", "उत्तररामचरित", "अभिज्ञानशाकुंतलम्"], "correct": 1, "category": "literature"},
    {"question": "'देवदास' के लेखक कौन हैं?", "options": ["बंकिमचंद्र चट्टोपाध्याय", "शरतचंद्र चट्टोपाध्याय", "रविंद्रनाथ टैगोर", "प्रेमचंद"], "correct": 1, "category": "literature"},
    {"question": "कालिदास की प्रसिद्ध कृति कौन सी है?", "options": ["रामायण", "महाभारत", "अभिज्ञानशाकुंतलम्", "पद्मावत"], "correct": 2, "category": "literature"},
    {"question": "'मुंशी प्रेमचंद' का असली नाम क्या था?", "options": ["धनपत राय", "नवाब राय", "प्रेम राय", "मुंशी राय"], "correct": 0, "category": "literature"},
    {"question": "जयशंकर प्रसाद की प्रसिद्ध कृति कौन सी है?", "options": ["मालती माधव", "कामायनी", "परिणय", "आंसू"], "correct": 1, "category": "literature"},
    {"question": "'पंचतंत्र' के लेखक कौन हैं?", "options": ["विष्णु शर्मा", "कालिदास", "भास", "भवभूति"], "correct": 0, "category": "literature"},
    {"question": "सूर्यकांत त्रिपाठी 'निराला' की कृति कौन सी है?", "options": ["अनामिका", "राज्यश्री", "तुलसी-दास", "प्रिय-प्रवास"], "correct": 0, "category": "literature"},
    {"question": "महादेवी वर्मा की कृति कौन सी है?", "options": ["यामा", "अतीत के चलचित्र", "शृंगार", "मेरी असफलताएं"], "correct": 0, "category": "literature"},
    # 40-49
    {"question": "15 x 4 का मान क्या है?", "options": ["50", "60", "70", "80"], "correct": 1, "category": "math"},
    {"question": "100 ÷ 5 का मान क्या है?", "options": ["15", "20", "25", "30"], "correct": 1, "category": "math"},
    {"question": "वर्ग का क्षेत्रफल क्या होता है?", "options": ["भुजा²", "भुजा x 4", "भुजा x 2", "भुजा + 4"], "correct": 0, "category": "math"},
    {"question": "एक मीटर में कितने सेंटीमीटर होते हैं?", "options": ["10", "50", "100", "1000"], "correct": 2, "category": "math"},
    {"question": "3² का मान क्या है?", "options": ["6", "8", "9", "12"], "correct": 2, "category": "math"},
    {"question": "√16 का मान क्या है?", "options": ["2", "3", "4", "5"], "correct": 2, "category": "math"},
    {"question": "50% का मान 200 में क्या है?", "options": ["50", "75", "100", "125"], "correct": 2, "category": "math"},
    {"question": "एक दर्जन में कितनी चीजें होती हैं?", "options": ["10", "12", "15", "20"], "correct": 1, "category": "math"},
    {"question": "पाई (π) का अनुमानित मान क्या है?", "options": ["2.14", "3.14", "4.14", "5.14"], "correct": 1, "category": "math"},
    {"question": "25 + 75 का मान क्या है?", "options": ["90", "95", "100", "105"], "correct": 2, "category": "math"},
    # 50-59
    {"question": "क्रिकेट में एक पारी में कितने विकेट होते हैं?", "options": ["9", "10", "11", "12"], "correct": 1, "category": "sports"},
    {"question": "फुटबॉल का खेल कब शुरू हुआ?", "options": ["1850", "1863", "1875", "1880"], "correct": 1, "category": "sports"},
    {"question": "ओलंपिक खेलों का आयोजन कितने साल में होता है?", "options": ["2 साल", "3 साल", "4 साल", "5 साल"], "correct": 2, "category": "sports"},
    {"question": "टेनिस कोर्ट में कितने लाइन होते हैं?", "options": ["8", "10", "12", "14"], "correct": 2, "category": "sports"},
    {"question": "बैडमिंटन का नेट कितना ऊंचा होता है?", "options": ["1.5 मीटर", "1.7 मीटर", "1.9 मीटर", "2.1 मीटर"], "correct": 2, "category": "sports"},
    {"question": "हॉकी की स्टिक का वजन कितना होता है?", "options": ["300 ग्राम", "500 ग्राम", "700 ग्राम", "900 ग्राम"], "correct": 1, "category": "sports"},
    {"question": "वॉलीबॉल कोर्ट में कितने खिलाड़ी होते हैं?", "options": ["5", "6", "7", "8"], "correct": 1, "category": "sports"},
    {"question": "बास्केटबॉल का गोल कितना ऊंचा होता है?", "options": ["2.5 मीटर", "3 मीटर", "3.05 मीटर", "3.5 मीटर"], "correct": 2, "category": "sports"},
    {"question": "कुश्ती के मैट का आकार कितना होता है?", "options": ["8x8", "9x9", "10x10", "12x12"], "correct": 0, "category": "sports"},
    {"question": "तैराकी के ओलंपिक पूल की लंबाई कितनी है?", "options": ["25 मीटर", "40 मीटर", "50 मीटर", "75 मीटर"], "correct": 2, "category": "sports"},
    # 60-69
    {"question": "मानव शरीर का सबसे बड़ा अंग कौन सा है?", "options": ["दिल", "दिमाग", "यकृत", "त्वचा"], "correct": 3, "category": "biology"},
    {"question": "मानव शरीर में कितनी पसलियां होती हैं?", "options": ["20", "22", "24", "26"], "correct": 2, "category": "biology"},
    {"question": "रक्त का तापमान कितना होता है?", "options": ["34°C", "35°C", "36°C", "37°C"], "correct": 3, "category": "biology"},
    {"question": "हृदय की धड़कन प्रति मिनट कितनी होनी चाहिए?", "options": ["50-60", "60-80", "80-100", "100-120"], "correct": 1, "category": "biology"},
    {"question": "फेफड़ों में कितने वायु कोष होते हैं?", "options": ["300 मिलियन", "500 मिलियन", "700 मिलियन", "900 मिलियन"], "correct": 0, "category": "biology"},
    {"question": "मानव दांत कितनी बार बदलते हैं?", "options": ["1 बार", "2 बार", "3 बार", "4 बार"], "correct": 1, "category": "biology"},
    {"question": "आंख में कितनी मांसपेशियां होती हैं?", "options": ["4", "6", "8", "10"], "correct": 1, "category": "biology"},
    {"question": "जीभ में कितनी स्वाद कलियां होती हैं?", "options": ["500", "1000", "5000", "10000"], "correct": 2, "category": "biology"},
    {"question": "मानव DNA में कितने गुणसूत्र होते हैं?", "options": ["44", "46", "48", "50"], "correct": 1, "category": "biology"},
    {"question": "बड़ी आंत की लंबाई कितनी होती है?", "options": ["3 फीट", "4 फीट", "5 फीट", "6 फीट"], "correct": 3, "category": "biology"},
    # 70-79
    {"question": "भारतीय चित्रकला की प्रसिद्ध शैली कौन सी है?", "options": ["मुगल", "राजस्थानी", "बंगाल", "सभी"], "correct": 3, "category": "art"},
    {"question": "ताज महल किस शैली का उदाहरण है?", "options": ["इस्लामिक", "हिंदू", "बौद्ध", "सिख"], "correct": 0, "category": "art"},
    {"question": "भरतनाट्यम किस प्रांत का शास्त्रीय नृत्य है?", "options": ["कर्नाटक", "तमिलनाडु", "केरल", "उड़ीसा"], "correct": 1, "category": "art"},
    {"question": "कथक नृत्य किस क्षेत्र से संबंधित है?", "options": ["पश्चिम बंगाल", "महाराष्ट्र", "उत्तर भारत", "दक्षिण भारत"], "correct": 2, "category": "art"},
    {"question": "ओडिसी नृत्य किस राज्य की परंपरा है?", "options": ["बिहार", "उड़ीसा", "झारखंड", "पश्चिम बंगाल"], "correct": 1, "category": "art"},
    {"question": "मोहनजोदड़ो किस सभ्यता का प्रमुख नगर था?", "options": ["वैदिक", "सिंधु घाटी", "मौर्य", "गुप्त"], "correct": 1, "category": "art"},
    {"question": "अजंता गुफाएं किस धर्म से संबंधित हैं?", "options": ["हिंदू", "बौद्ध", "जैन", "सिख"], "correct": 1, "category": "art"},
    {"question": "एलोरा गुफाएं कहां स्थित हैं?", "options": ["कर्नाटक", "महाराष्ट्र", "गुजरात", "मध्य प्रदेश"], "correct": 1, "category": "art"},
    {"question": "सांची स्तूप किस राज्य में है?", "options": ["राजस्थान", "मध्य प्रदेश", "गुजरात", "उत्तर प्रदेश"], "correct": 1, "category": "art"},
    {"question": "कोणार्क का सूर्य मंदिर किस राज्य में है?", "options": ["बिहार", "उड़ीसा", "झारखंड", "पश्चिम बंगाल"], "correct": 1, "category": "art"},
    # 80-89
    {"question": "तिब्बत की सबसे ऊंची चोटी कौन सी है?", "options": ["कंचनजंगा", "नंदा देवी", "चोमोलुंगमा", "अन्नपूर्णा"], "correct": 2, "category": "geography"},
    {"question": "कार्बन की परमाणु संख्या क्या है?", "options": ["6", "8", "12", "14"], "correct": 0, "category": "science"},
    {"question": "सूरदास किसके भक्त थे?", "options": ["शिव", "कृष्ण", "विष्णु", "देवी"], "correct": 1, "category": "literature"},
    {"question": "चेन्नई किस राज्य की राजधानी है?", "options": ["कर्नाटक", "तमिलनाडु", "आंध्र प्रदेश", "तेलंगाना"], "correct": 1, "category": "geography"},
    {"question": "200 का 50% क्या है?", "options": ["50", "75", "100", "150"], "correct": 2, "category": "math"},
    {"question": "सबसे हल्की धातु कौन सी है?", "options": ["एलुमीनियम", "लिथियम", "मैग्नीशियम", "जिंक"], "correct": 1, "category": "science"},
    {"question": "राजस्थान का सबसे बड़ा शहर कौन सा है?", "options": ["जयपुर", "जोधपुर", "बीकानेर", "अजमेर"], "correct": 0, "category": "geography"},
    {"question": "इंडिया गेट किस शहर में है?", "options": ["मुंबई", "बेंगलुरु", "दिल्ली", "कोलकाता"], "correct": 2, "category": "geography"},
    {"question": "गायत्री मंत्र किस वेद में है?", "options": ["ऋग्वेद", "यजुर्वेद", "सामवेद", "अथर्ववेद"], "correct": 0, "category": "literature"},
    {"question": "पृथ्वी के चारों ओर कितने महासागर हैं?", "options": ["3", "4", "5", "6"], "correct": 2, "category": "geography"},
    # 90-99
    {"question": "फूलों का राजा किसे कहते हैं?", "options": ["कमल", "गुलाब", "गेंदा", "कनेर"], "correct": 1, "category": "biology"},
    {"question": "भारत का सबसे ऊंचा बांध कौन सा है?", "options": ["दामोदर", "नर्मदा", "भाखड़ा", "सरदार सरोवर"], "correct": 3, "category": "geography"},
    {"question": "नोबेल पुरस्कार किस देश में शुरू हुआ?", "options": ["जर्मनी", "स्वीडन", "अमेरिका", "इंग्लैंड"], "correct": 1, "category": "history"},
    {"question": "रक्त का रंग लाल क्यों होता है?", "options": ["हीमोग्लोबिन", "प्लाज्मा", "प्लेटलेट्स", "लिकोसाइट्स"], "correct": 0, "category": "biology"},
    {"question": "बिहार की राजधानी कौन सी है?", "options": ["पटना", "मुजफ्फरपुर", "दरभंगा", "गया"], "correct": 0, "category": "geography"},
    {"question": "सूरज से पृथ्वी की दूरी कितनी है?", "options": ["100 मिलियन किमी", "150 मिलियन किमी", "200 मिलियन किमी", "250 मिलियन किमी"], "correct": 1, "category": "science"},
    {"question": "बर्फ किसकी अवस्था है?", "options": ["तरल", "ठोस", "गैस", "प्लाज्मा"], "correct": 1, "category": "science"},
    {"question": "भारत की सबसे बड़ी झील कौन सी है?", "options": ["वुलर", "लोकतक", "कोलेरू", "सांभर"], "correct": 3, "category": "geography"},
    {"question": "किस फूल को जल का फूल कहते हैं?", "options": ["कमल", "कुमुद", "सरोवर", "जलकुंभी"], "correct": 0, "category": "biology"},
    {"question": "पेड़ों का राजा किसे कहते हैं?", "options": ["नीम", "बरगद", "आम", "पीपल"], "correct": 1, "category": "biology"},
]

# Combine all questions
ALL_QUESTIONS = {
    'english': ENGLISH_QUESTIONS,
    'hindi': HINDI_QUESTIONS,
}

def get_random_questions(language='english', count=20):
    """
    Get random questions from the static pool
    """
    import random
    language = language.lower()
    questions_pool = ALL_QUESTIONS.get(language, ALL_QUESTIONS['english'])
    shuffled = random.sample(questions_pool, min(count, len(questions_pool)))
    return shuffled
