# Generated by Django 5.0 on 2025-12-08 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("text", "Text"),
                            ("image", "Image"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField()),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("total_questions", models.IntegerField(default=5)),
                (
                    "estimated_time",
                    models.IntegerField(help_text="Estimated time in minutes"),
                ),
                ("keywords", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(default="anonymous", max_length=255)),
                ("attempts", models.IntegerField(default=0)),
                ("best_score", models.FloatField(blank=True, null=True)),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("analysis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="question_solver.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserQuizResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(default="anonymous", max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_taken",
                    models.IntegerField(
                        blank=True, help_text="Time taken in seconds", null=True
                    ),
                ),
                ("responses", models.JSONField(default=dict)),
                ("score", models.FloatField(blank=True, null=True)),
                ("correct_answers", models.IntegerField(default=0)),
                ("total_answers", models.IntegerField(default=0)),
                ("feedback", models.TextField(blank=True)),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_responses",
                        to="question_solver.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("matching", "Matching"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField()),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.CharField(blank=True, max_length=500)),
                ("explanation", models.TextField(blank=True)),
                ("hint", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="question_solver.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["quiz", "order"],
                "unique_together": {("quiz", "order")},
            },
        ),
    ]
