# Generated by Django 5.0 on 2025-12-09 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[("free", "Free"), ("premium", "Premium")],
                        default="free",
                        max_length=50,
                    ),
                ),
                ("ask_questions_used", models.IntegerField(default=0)),
                ("quiz_generated", models.IntegerField(default=0)),
                ("flashcards_generated", models.IntegerField(default=0)),
                ("auto_pay_enabled", models.BooleanField(default=False)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("subscription_start_date", models.DateTimeField(auto_now_add=True)),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                ("next_billing_date", models.DateTimeField(blank=True, null=True)),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                ("usage_reset_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="question_so_user_id_f4f750_idx"
                    ),
                    models.Index(fields=["plan"], name="question_so_plan_c8d7ea_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(max_length=50)),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                ("billing_cycle_start", models.DateTimeField()),
                ("billing_cycle_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="question_solver.usersubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "-created_at"],
                        name="question_so_subscri_2311e1_idx",
                    ),
                    models.Index(
                        fields=["status"], name="question_so_status_77c8c1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeatureUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_name", models.CharField(max_length=50)),
                ("usage_type", models.CharField(max_length=20)),
                (
                    "input_size",
                    models.IntegerField(help_text="Size in characters or bytes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="question_solver.usersubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "-created_at"],
                        name="question_so_subscri_b0a7d5_idx",
                    ),
                    models.Index(
                        fields=["feature_name"], name="question_so_feature_806f9f_idx"
                    ),
                ],
            },
        ),
    ]
