# Generated by Django 5.0 on 2025-12-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0002_add_razorpay_fields"),
        ("question_solver", "0002_usersubscription_payment_featureusagelog"),
    ]

    operations = []
