# Generated by Django 5.0 on 2025-12-14 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0003_merge_20251209_1240"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                ("total_questions", models.IntegerField(default=10)),
                ("coins_per_correct", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Daily Quizzes",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserCoins",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("total_coins", models.IntegerField(default=0)),
                ("lifetime_coins", models.IntegerField(default=0)),
                ("coins_spent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "User Coins",
                "ordering": ["-total_coins"],
            },
        ),
        migrations.CreateModel(
            name="CoinTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earned"),
                            ("spend", "Spent"),
                            ("bonus", "Bonus"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_coins",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="question_solver.usercoins",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField()),
                ("question_text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Knowledge"),
                            ("current_events", "Current Events"),
                            ("science", "Science"),
                            ("history", "History"),
                            ("geography", "Geography"),
                            ("sports", "Sports"),
                            ("entertainment", "Entertainment"),
                            ("technology", "Technology"),
                            ("politics", "Politics"),
                            ("economics", "Economics"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Easy"), ("moderate", "Moderate")],
                        default="easy",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.CharField(max_length=10)),
                ("explanation", models.TextField(blank=True)),
                ("fun_fact", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="question_solver.dailyquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["daily_quiz", "order"],
                "unique_together": {("daily_quiz", "order")},
            },
        ),
        migrations.CreateModel(
            name="UserDailyQuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("answers", models.JSONField(default=dict)),
                ("correct_count", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=10)),
                ("score_percentage", models.FloatField(default=0.0)),
                ("coins_earned", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_taken_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "daily_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="question_solver.dailyquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "-started_at"],
                        name="question_so_user_id_79708e_idx",
                    )
                ],
                "unique_together": {("daily_quiz", "user_id")},
            },
        ),
    ]
