# Generated by Django 5.0 on 2025-12-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="question_so_token_f3cb3a_idx",
            old_name="question_so_token_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="question_so_user_id_bd9752_idx",
            old_name="question_so_user_id_created_at_idx",
        ),
    ]
