# Generated by Django 5.0 on 2025-12-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0007_pairquizsession"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pairquizsession",
            new_name="question_so_session_2196f0_idx",
            old_name="question_so_session_b3c4f1_idx",
        ),
        migrations.RenameIndex(
            model_name="pairquizsession",
            new_name="question_so_status_406972_idx",
            old_name="question_so_status_a7e2d9_idx",
        ),
        migrations.RenameIndex(
            model_name="pairquizsession",
            new_name="question_so_host_us_338500_idx",
            old_name="question_so_host_us_c8f3a1_idx",
        ),
    ]
