# Generated by Django 5.0 on 2025-12-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "question_solver",
            "0008_rename_question_so_session_b3c4f1_idx_question_so_session_2196f0_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_quiz_attempt_bonus",
                    models.IntegerField(
                        default=5, help_text="Coins awarded for starting a daily quiz"
                    ),
                ),
                (
                    "daily_quiz_coins_per_correct",
                    models.IntegerField(
                        default=5,
                        help_text="Coins awarded per correct answer in daily quiz",
                    ),
                ),
                (
                    "daily_quiz_perfect_score_bonus",
                    models.IntegerField(
                        default=10, help_text="Extra bonus coins for getting 100% score"
                    ),
                ),
                (
                    "pair_quiz_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable/disable pair quiz feature"
                    ),
                ),
                (
                    "pair_quiz_session_timeout",
                    models.IntegerField(
                        default=30, help_text="Session expiry time in minutes"
                    ),
                ),
                (
                    "pair_quiz_max_questions",
                    models.IntegerField(
                        default=20, help_text="Maximum questions allowed per quiz"
                    ),
                ),
                (
                    "coin_to_currency_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.1,
                        help_text="Conversion rate: 1 coin = X currency",
                        max_digits=10,
                    ),
                ),
                (
                    "min_coins_for_redemption",
                    models.IntegerField(
                        default=100, help_text="Minimum coins required for redemption"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Quiz Settings",
                "verbose_name_plural": "Quiz Settings",
            },
        ),
    ]
