# Generated by Django 5.0 on 2025-12-20 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0009_quizsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "razorpay_order_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paise", models.IntegerField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("attempted", "Attempted"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                ("receipt", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.JSONField(blank=True, default=dict)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "payment_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "-created_at"],
                        name="question_so_user_id_d050df_idx",
                    ),
                    models.Index(
                        fields=["status"], name="question_so_status_464acf_idx"
                    ),
                    models.Index(
                        fields=["razorpay_order_id"],
                        name="question_so_razorpa_015945_idx",
                    ),
                ],
            },
        ),
    ]
