# Generated by Django 5.0 on 2025-12-20 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0010_razorpayorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinWithdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("coins_amount", models.IntegerField()),
                ("rupees_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payout_amount", models.IntegerField()),
                ("account_holder_name", models.CharField(max_length=255)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=20, null=True)),
                ("upi_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "payout_method",
                    models.CharField(
                        choices=[("bank", "Bank Transfer"), ("upi", "UPI")],
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_payout_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "razorpay_fund_account_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_contact_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "status"],
                        name="question_so_user_id_e5791f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="question_so_created_abe9fc_idx"
                    ),
                ],
            },
        ),
    ]
