# Generated by Django 5.0 on 2025-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0011_coinwithdrawal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cointransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("earn", "Earned"),
                    ("spend", "Spent"),
                    ("bonus", "Bonus"),
                    ("refund", "Refund"),
                    ("withdrawal", "Withdrawal"),
                ],
                max_length=20,
            ),
        ),
    ]
