# Generated by Django 5.0 on 2025-12-22 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0012_add_withdrawal_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cointransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("earn", "Earned"),
                    ("spend", "Spent"),
                    ("bonus", "Bonus"),
                    ("refund", "Refund"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quizsettings",
            name="min_coins_for_redemption",
            field=models.IntegerField(
                default=10, help_text="Minimum coins required for redemption"
            ),
        ),
        migrations.CreateModel(
            name="PlanSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("FREE", "Free Plan"), ("PAID", "Paid Plan")],
                        default="FREE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_subscription_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "razorpay_plan_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "plan_subscription",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="plan_subscr_user_id_b75967_idx"
                    ),
                    models.Index(
                        fields=["plan_type", "status"],
                        name="plan_subscr_plan_ty_497ff1_idx",
                    ),
                    models.Index(
                        fields=["razorpay_subscription_id"],
                        name="plan_subscr_razorpa_47aa80_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageQuota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("quizzes_used", models.IntegerField(default=0)),
                ("mock_tests_used", models.IntegerField(default=0)),
                ("flashcards_used", models.IntegerField(default=0)),
                ("predicted_questions_used", models.IntegerField(default=0)),
                ("youtube_summaries_used", models.IntegerField(default=0)),
                ("last_reset_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "usage_quota",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="usage_quota_user_id_1027a5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("razorpay_payment_id", models.CharField(max_length=255, unique=True)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("billing_period_start", models.DateTimeField()),
                ("billing_period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="question_solver.plansubscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_payment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "-created_at"],
                        name="subscriptio_subscri_a127f5_idx",
                    ),
                    models.Index(
                        fields=["razorpay_payment_id"],
                        name="subscriptio_razorpa_9192ae_idx",
                    ),
                    models.Index(
                        fields=["status"], name="subscriptio_status_9c1a5d_idx"
                    ),
                ],
            },
        ),
    ]
