# Generated by Django 5.0 on 2025-12-24 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0013_alter_cointransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubscription",
            old_name="ask_questions_used",
            new_name="flashcards_used",
        ),
        migrations.RenameField(
            model_name="usersubscription",
            old_name="flashcards_generated",
            new_name="mock_test_used",
        ),
        migrations.RenameField(
            model_name="usersubscription",
            old_name="quiz_generated",
            new_name="pair_quiz_used",
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="ask_question_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="daily_quiz_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="predicted_questions_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="previous_papers_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="pyq_features_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="quiz_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="razorpay_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="youtube_summarizer_used",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("free", "Free"), ("premium", "Premium")],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "first_month_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "recurring_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "mock_test_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                (
                    "quiz_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                (
                    "pair_quiz_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                (
                    "flashcards_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                (
                    "ask_question_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                (
                    "predicted_questions_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                (
                    "previous_papers_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                (
                    "pyq_features_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                (
                    "youtube_summarizer_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                (
                    "daily_quiz_limit",
                    models.IntegerField(
                        blank=True, help_text="null = unlimited", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["first_month_price"],
                "indexes": [
                    models.Index(fields=["name"], name="question_so_name_2e05fb_idx"),
                    models.Index(
                        fields=["is_active"], name="question_so_is_acti_43cfae_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="question_solver.subscriptionplan",
            ),
        ),
    ]
