# Generated by Django 5.0 on 2025-12-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "question_solver",
            "0014_rename_ask_questions_used_usersubscription_flashcards_used_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="auto_pay_enabled",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="daily_quiz_used",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="pair_quiz_used",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="previous_papers_used",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="pyq_features_used",
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="pyqs_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="razorpay_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                    ("paused", "Paused"),
                ],
                default="active",
                max_length=50,
            ),
        ),
    ]
