# Generated by Django 5.0 on 2026-01-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0016_refactor_withdrawal_upi_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cointransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("earn", "Earned"),
                    ("spend", "Spent"),
                    ("bonus", "Bonus"),
                    ("refund", "Refund"),
                    ("withdrawal", "Withdrawal"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coinwithdrawal",
            name="coins_amount",
            field=models.IntegerField(help_text="Coins to withdraw (min: 100)"),
        ),
        migrations.AlterField(
            model_name="coinwithdrawal",
            name="rupees_amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Amount in rupees (coins/10)", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[("basic", "BASIC"), ("premium", "PREMIUM")],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="plan",
            field=models.CharField(
                choices=[("basic", "BASIC"), ("premium", "PREMIUM")],
                default="basic",
                max_length=50,
            ),
        ),
    ]
