# Generated by Django 5.0 on 2026-01-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0017_alter_cointransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="daily_quiz_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="pair_quiz_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="previous_papers_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[("free", "FREE"), ("basic", "BASIC"), ("premium", "PREMIUM")],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="plan",
            field=models.CharField(
                choices=[("free", "FREE"), ("basic", "BASIC"), ("premium", "PREMIUM")],
                default="free",
                max_length=50,
            ),
        ),
    ]
