# Generated by Django 5.0 on 2026-01-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0018_usersubscription_daily_quiz_used_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userdailyquizattempt",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="userdailyquizattempt",
            index=models.Index(
                fields=["daily_quiz", "user_id"], name="question_so_daily_q_946c0c_idx"
            ),
        ),
    ]
