# Generated by Django 5.0 on 2026-01-14 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0019_allow_multiple_daily_quiz_attempts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("hour", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("closes", models.IntegerField(default=0)),
                ("failures", models.IntegerField(default=0)),
                ("feature", models.CharField(blank=True, max_length=100)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "ad_analytics",
                "ordering": ["-date", "-hour"],
                "indexes": [
                    models.Index(fields=["date"], name="ad_analytic_date_545ef3_idx"),
                    models.Index(
                        fields=["feature"], name="ad_analytic_feature_c50b9b_idx"
                    ),
                    models.Index(
                        fields=["platform"], name="ad_analytic_platfor_1a455c_idx"
                    ),
                ],
                "unique_together": {("date", "hour", "feature", "platform")},
            },
        ),
        migrations.CreateModel(
            name="FeatureAdConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_name", models.CharField(max_length=100, unique=True)),
                ("feature_display_name", models.CharField(max_length=200)),
                (
                    "show_ad_after_use",
                    models.BooleanField(
                        default=True, help_text="Show ad after feature use"
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("interstitial", "Interstitial"),
                            ("rewarded", "Rewarded"),
                            ("banner", "Banner"),
                        ],
                        default="interstitial",
                        max_length=20,
                    ),
                ),
                (
                    "show_frequency",
                    models.IntegerField(
                        default=1, help_text="Show ad every N uses (1 = every use)"
                    ),
                ),
                ("ios_placement_id", models.CharField(blank=True, max_length=100)),
                ("android_placement_id", models.CharField(blank=True, max_length=100)),
                ("skip_for_premium", models.BooleanField(default=True)),
                ("skip_if_ad_seen_today", models.BooleanField(default=False)),
                ("max_ads_per_day", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "feature_ad_config",
                "ordering": ["feature_name"],
                "indexes": [
                    models.Index(
                        fields=["feature_name"], name="feature_ad__feature_658efa_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="feature_ad__is_acti_87f216_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdImpressionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("interstitial", "Interstitial"),
                            ("rewarded", "Rewarded"),
                            ("banner", "Banner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        default="ios",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("shown", "Shown"),
                            ("clicked", "Clicked"),
                            ("closed", "Closed"),
                            ("failed", "Failed"),
                        ],
                        default="shown",
                        max_length=20,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        help_text="Feature that triggered the ad", max_length=100
                    ),
                ),
                ("unity_placement_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_impressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ad_impression_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ad_impressi_user_id_632e78_idx",
                    ),
                    models.Index(
                        fields=["ad_type", "-created_at"],
                        name="ad_impressi_ad_type_3f1acf_idx",
                    ),
                    models.Index(
                        fields=["feature"], name="ad_impressi_feature_da1926_idx"
                    ),
                    models.Index(
                        fields=["status"], name="ad_impressi_status_ec23f1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAdLimitTracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ads_shown_today", models.IntegerField(default=0)),
                ("last_ad_reset", models.DateTimeField(auto_now_add=True)),
                ("feature_use_counts", models.JSONField(blank=True, default=dict)),
                ("last_ad_shown", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_limit_tracker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_ad_limit_tracker",
                "indexes": [
                    models.Index(fields=["user"], name="user_ad_lim_user_id_284690_idx")
                ],
            },
        ),
    ]
